### ISSUE TITLE
save cigar string

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [RagnarGrootKoerkamp/astar-pairwise-aligner#15]
write edit distances and cigar strings to a file, similar to wfa

**Comment by AndreaGuarracino** [comment]
Also an output in `PAF` format would be quite polite.

**Comment by RagnarGrootKoerkamp** [comment]
Hmm, what information could I store in there? https://github.com/lh3/miniasm/blob/master/PAF.md

It seems to be useful for mapping only, and pretty much useless for global alignment. It doesn't contain the alignment score and also not the cigar string, which are the only 2 useful pieces of output I have.

**Comment by AndreaGuarracino** [comment]
After the first 12 columns, the PAF format is a bit wild. Aligners usually put each piece of information in a dedicated column. The  CIGAR string becomes `cg:Z:3=1X14=1X5=4X1...`.

But agreed that it is not fundamental. I use scripts that take the output of WFA (query length, target length, score, CIGAR string) and write them in a PAF-like row.

**Comment by RagnarGrootKoerkamp** [comment]
The binary [supports](https://github.com/RagnarGrootKoerkamp/astar-pairwise-aligner/blob/80cd424012b27a364cd7340b0751aefacb95ea19/pa-bin/src/cli.rs#L26-L28) this now via `--output file.csv` which has one line of the form `{cost},{cigar}` per input pair.
