### ISSUE TITLE
sequence identity down to 90%?

### ISSUE THREAD

**Issue by jianshu93** [RagnarGrootKoerkamp/astar-pairwise-aligner#16]
Hello Team,

Thanks for the A*PA, bi-wfa aligns only highly identical sequences, e.g., 95% identical or above. The performance degrades quickly when identity goes below 90% or so. I am wondering is this also the case for A*PA since both are optimising find the best path in the dynamic programming table.

Thanks,

Jianshu

**Comment by pesho-ivanov** [comment]
Hey Jianshu!

Indeed, high error rate is challenging for all tools/algorithms. The evals of [preprint of BiWFA](https://www.biorxiv.org/content/10.1101/2022.04.14.488380), run up to 2 Mbp and 20% error rate. Note that its runtime asymptotics is O(e*n^2), where e=20%.

In our case it is not as easy to give an asymptotic guarantee but the reason why A\*PA _could_ be faster is that it needs to calculate only a fraction of the DP table. In the [A*PA preprint](https://www.biorxiv.org/content/10.1101/2022.09.19.508631) observed that for 10% uniform errors, it scales near-linearly up to 10 Mbp (Fig.4c). For shorter sequences (n=10000), we can handle fast up to 25% errors (App. Fig.6b). Note that A*PA is much more dependent on the distribution of errors so for real ONT sequences we are must slower for part of the sequences even though for others we are faster (Fig.5).

In essence, A*PA is still work in progress until it becomes a production-ready instrument. But we are going there. :")

Pesho
