### ISSUE TITLE
SDL2 linker error

### ISSUE THREAD

**Issue by valentynbez** [RagnarGrootKoerkamp/astar-pairwise-aligner#19]
Hi, 
I was trying to test your library and got the following error:
```
binutils/2.37/bin/ld.gold: error: cannot find -lSDL2
binutils/2.37/bin/ld.gold: error: cannot find -lSDL2_ttf
```

Tried to install SDL2 library and add it to `LD_LIBRARY_PATH` - no effect. 
I am not a Rust-savvy person, how can I point the compiler to a required file?

**Comment by RagnarGrootKoerkamp** [comment]
You should be able to compile with --no-default-features, which disabled the visualization part of the code and hence should not need SDL2 as a dependency.

**Comment by RagnarGrootKoerkamp** [comment]
Otherwise, I know other people had no issues after installing the system-wide SDL2 package via their package manager.

**Comment by valentynbez** [comment]
Figured it out. 
Unfortunately, I wasn't able to do a system-wide install of SDL2, because I was working on cluster, where I don't have permissions to modify stuff inside `/usr/` :( 
I added a `build.rs` in `pa-vis` with following content: 
```
fn main () {
    #[cfg(target_os="linux")]
    println!("cargo:rustc-link-search=/link/to/libraries")
}
```

Leaving it as solution if anyone gets lost :)

**Comment by RagnarGrootKoerkamp** [comment]
Ah, that is a nice workaround :)
But still, if you don't need the visualizations it should work fine without SDL2 at all ;)
